/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jemalloctest_JemallocIntegration */

#ifndef _Included_jemalloctest_JemallocIntegration
#define _Included_jemalloctest_JemallocIntegration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jemalloctest_JemallocIntegration
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jemalloctest_JemallocIntegration_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
